### ISSUE TITLE
Objects exported from a group in Maya cause a crash

### ISSUE THREAD

**Issue by AlexTsekot** [MaxxWyndham/Flummery#114]
If an object is parented to a null node (a group in Maya) and is selected and exported to FBX, an unhandled exception occurs. Not sure if it's a maya specific issue. If the object is parented to an empty 'group' this error occurs, however everything imports fine if the parent object is a mesh and not an empty node (group).

"Object not set to an instance of an object"

*************\* Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Flummery.ModelManipulator.FlipAxis(ModelMesh model, Axis axis, Boolean bApplyToHierarchy)
   at Flummery.ContentPipeline.Core.FBXImporter.Import(String path)
   at Flummery.ContentManager.Load[T,T2](String assetName, String assetPath, Boolean bAddToScene)
   at Flummery.frmMain.menuImportClick(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by MaxxWyndham** [comment]
See #85
